from backend.memory.write_pipeline.background_recorder import (
    BackgroundMemoryRecorder,
    BackgroundRecordResult,
    ShadowCandidate,
)
"""Versioned semantic-memory write domain.

Standard-library-only contracts, registry, resolver, and policy for the
first canonical key. No database, HTTP, worker, or model dependency.
"""

from backend.memory.write_pipeline.models import (
    AUTHORITY_RANK,
    CANDIDATE_ID_PREFIX,
    DECISION_ID_PREFIX,
    EVIDENCE_ID_PREFIX,
    SENSITIVITY_RANK,
    VERSION_ID_PREFIX,
    AssertionIdentity,
    Authority,
    Cardinality,
    DecisionOutcome,
    DecisionReason,
    MemoryCandidate,
    MemoryChangeSet,
    MemoryDecision,
    MemoryDecisionDraft,
    MemoryEvidence,
    MemoryOperation,
    MemoryRelation,
    MemoryScope,
    MemoryVersion,
    MemoryVersionDraft,
    SensitivityBand,
    VersionStatus,
    assertion_identity,
    new_candidate_id,
    new_evidence_id,
    new_version_id,
)
from backend.memory.write_pipeline.policy import (
    Actor,
    DecisionContext,
    EligibilityOutcome,
    Origin,
    classify_sensitivity,
    decide_candidate,
    evaluate_eligibility,
)
from backend.memory.write_pipeline.registry import (
    HOTEL_ATMOSPHERE_DEFINITION,
    HOTEL_ATMOSPHERE_KEY,
    HOTEL_ATMOSPHERE_SYNONYMS,
    SEMANTIC_REGISTRY_VERSION,
    HotelAtmosphere,
    SemanticKeyDefinition,
    UnknownKeyError,
    UnknownValueError,
    get_key_definition,
    is_known_key,
    normalize_value,
)
from backend.memory.write_pipeline.resolver import resolve_change
from backend.memory.write_pipeline.secrets import (
    DETECTOR_VERSION,
    REDACTED_MARK,
    ProhibitedFinding,
    ProhibitedKind,
    detect_prohibited_content,
)

__all__ = [
    "AUTHORITY_RANK",
    "CANDIDATE_ID_PREFIX",
    "DECISION_ID_PREFIX",
    "DETECTOR_VERSION",
    "EVIDENCE_ID_PREFIX",
    "HOTEL_ATMOSPHERE_DEFINITION",
    "HOTEL_ATMOSPHERE_KEY",
    "HOTEL_ATMOSPHERE_SYNONYMS",
    "SEMANTIC_REGISTRY_VERSION",
    "SENSITIVITY_RANK",
    "VERSION_ID_PREFIX",
    "Actor",
    "BackgroundMemoryRecorder",
    "BackgroundRecordResult",
    "AssertionIdentity",
    "Authority",
    "Cardinality",
    "DecisionContext",
    "DecisionOutcome",
    "DecisionReason",
    "EligibilityOutcome",
    "HotelAtmosphere",
    "MemoryCandidate",
    "MemoryChangeSet",
    "MemoryDecision",
    "MemoryDecisionDraft",
    "MemoryEvidence",
    "MemoryOperation",
    "MemoryRelation",
    "MemoryScope",
    "MemoryVersion",
    "MemoryVersionDraft",
    "Origin",
    "ProhibitedFinding",
    "ProhibitedKind",
    "REDACTED_MARK",
    "SemanticKeyDefinition",
    "ShadowCandidate",
    "SensitivityBand",
    "UnknownKeyError",
    "UnknownValueError",
    "VersionStatus",
    "assertion_identity",
    "classify_sensitivity",
    "decide_candidate",
    "detect_prohibited_content",
    "evaluate_eligibility",
    "get_key_definition",
    "is_known_key",
    "new_candidate_id",
    "new_evidence_id",
    "new_version_id",
    "normalize_value",
    "resolve_change",
]
