"""Unit tests for the conversation and message value contracts.

These contracts are storage-agnostic and route-agnostic: the module under test
depends on the Python standard library only. Identity, ordering, and timestamps
are server-owned, so no caller-supplied value can set them.

No test here touches a database, a model provider, Chroma, or the network.
"""

import dataclasses
from datetime import datetime, timedelta, timezone

import pytest

import backend.conversations as conversations_package
from backend.conversations.models import (
    CONVERSATION_ID_PREFIX,
    DEFAULT_HISTORY_LIMIT,
    DEFAULT_MESSAGE_SOURCE,
    DEFAULT_RETENTION_STATE,
    DEFAULT_TRACE_VISIBILITY,
    MAX_HISTORY_LIMIT,
    MESSAGE_ID_PREFIX,
    PUBLIC_WRITABLE_ROLES,
    TITLE_MAX_LENGTH,
    Conversation,
    ConversationCreate,
    ConversationRetentionState,
    ConversationValidationError,
    Message,
    MessageDraft,
    MessageHistoryQuery,
    MessageRole,
    MessageSource,
    TraceVisibility,
    generate_conversation_id,
    generate_message_id,
    require_text,
    utc_now,
)

MOMENT = datetime(2026, 9, 4, 12, 0, 0, tzinfo=timezone.utc)


def _conversation(**overrides) -> Conversation:
    payload = {
        "conversation_id": generate_conversation_id(),
        "workspace_id": "tw_example",
        "title": "Da Nang food plan",
        "created_at": MOMENT,
        "updated_at": MOMENT,
    }
    payload.update(overrides)
    return Conversation(**payload)


def _draft(**overrides) -> MessageDraft:
    payload = {
        "conversation_id": "cv_example",
        "role": MessageRole.USER,
        "content": "Nên đi Đà Nẵng vào tháng mấy?",
        "created_at": MOMENT,
    }
    payload.update(overrides)
    return MessageDraft(**payload)


def _message(**overrides) -> Message:
    payload = {
        "message_id": generate_message_id(),
        "conversation_id": "cv_example",
        "sequence": 1,
        "role": MessageRole.USER,
        "content": "Nên đi Đà Nẵng vào tháng mấy?",
        "created_at": MOMENT,
    }
    payload.update(overrides)
    return Message(**payload)


def _field_names(contract: type) -> set[str]:
    return {item.name for item in dataclasses.fields(contract)}


# 1. Identity is generated by the module with governed prefixes.


def test_generated_identities_use_governed_prefixes():
    conversation_id = generate_conversation_id()
    message_id = generate_message_id()

    assert isinstance(conversation_id, str)
    assert isinstance(message_id, str)
    assert conversation_id.startswith(CONVERSATION_ID_PREFIX)
    assert message_id.startswith(MESSAGE_ID_PREFIX)
    assert CONVERSATION_ID_PREFIX == "cv_"
    assert MESSAGE_ID_PREFIX == "ms_"


def test_generated_identities_differ_across_calls():
    assert generate_conversation_id() != generate_conversation_id()
    assert generate_message_id() != generate_message_id()


def test_identity_prefix_is_enforced_on_rehydrated_records():
    with pytest.raises(ConversationValidationError):
        _conversation(conversation_id="tw_wrong_prefix")

    with pytest.raises(ConversationValidationError):
        _message(message_id="cv_wrong_prefix")


# 2. Identity and ordering cannot arrive from caller input.


def test_create_and_draft_contracts_expose_no_server_owned_fields():
    assert "conversation_id" not in _field_names(ConversationCreate)
    assert "message_id" not in _field_names(MessageDraft)
    assert "sequence" not in _field_names(MessageDraft)


# 3. `workspace_id` is stripped and required.


def test_workspace_id_is_stripped():
    assert (
        ConversationCreate(workspace_id="  tw_example  ").workspace_id == "tw_example"
    )
    assert _conversation(workspace_id="  tw_example  ").workspace_id == "tw_example"


@pytest.mark.parametrize("value", ["", "   ", None, 7])
def test_workspace_id_is_required(value):
    with pytest.raises(ConversationValidationError):
        ConversationCreate(workspace_id=value)


# 4 and 5. `title` is optional, stripped, bounded, and blank means absent.


def test_title_is_optional_and_stripped():
    assert ConversationCreate(workspace_id="tw_example").title is None
    assert (
        ConversationCreate(workspace_id="tw_example", title="  Da Nang  ").title
        == "Da Nang"
    )


@pytest.mark.parametrize("value", ["", "   ", "\n\t "])
def test_blank_title_normalizes_to_absent_rather_than_raising(value):
    assert ConversationCreate(workspace_id="tw_example", title=value).title is None
    assert _conversation(title=value).title is None


def test_title_at_the_maximum_length_is_accepted():
    exact = "t" * TITLE_MAX_LENGTH
    assert TITLE_MAX_LENGTH == 120
    assert ConversationCreate(workspace_id="tw_example", title=exact).title == exact


def test_title_over_the_maximum_length_raises():
    with pytest.raises(ConversationValidationError):
        ConversationCreate(
            workspace_id="tw_example", title="t" * (TITLE_MAX_LENGTH + 1)
        )

    with pytest.raises(ConversationValidationError):
        _conversation(title="t" * (TITLE_MAX_LENGTH + 1))


def test_non_string_title_raises():
    with pytest.raises(ConversationValidationError):
        ConversationCreate(workspace_id="tw_example", title=42)


# 6 and 7. `content` is required, and deliberately unbounded.


@pytest.mark.parametrize("value", ["", "   ", "\n", None, 7])
def test_content_is_required_and_non_blank(value):
    with pytest.raises(ConversationValidationError):
        _draft(content=value)

    with pytest.raises(ConversationValidationError):
        _message(content=value)


def test_content_is_stripped():
    assert _draft(content="  xin chào  ").content == "xin chào"


def test_content_has_no_maximum_length():
    """A deliberate departure from the R3 bounded-text rule, recorded in the spec.

    The chat route already accepts an unbounded `message`, so a storage limit
    would turn requests that succeed today into failures once a conversation is
    bound. Request size limiting belongs at the API boundary.
    """
    long_content = "a" * 100_000
    assert len(_draft(content=long_content).content) == 100_000
    assert len(_message(content=long_content).content) == 100_000


# 8. Governed vocabularies accept enum members and their string values.


@pytest.mark.parametrize(
    "role",
    [
        MessageRole.USER,
        MessageRole.ASSISTANT,
        MessageRole.TOOL,
        MessageRole.SYSTEM_EVENT,
    ],
)
def test_role_accepts_every_governed_member_and_its_string(role):
    assert _draft(role=role).role is role
    assert _draft(role=role.value).role is role


@pytest.mark.parametrize("value", ["admin", "Assistant", "USER", "", None, 3])
def test_role_rejects_any_ungoverned_value(value):
    with pytest.raises(ConversationValidationError):
        _draft(role=value)


@pytest.mark.parametrize("source", list(MessageSource))
def test_source_accepts_every_governed_member_and_its_string(source):
    assert _draft(source=source).source is source
    assert _draft(source=source.value).source is source


@pytest.mark.parametrize("value", ["browser", "Model", "", 3])
def test_source_rejects_any_ungoverned_value(value):
    with pytest.raises(ConversationValidationError):
        _draft(source=value)


@pytest.mark.parametrize("visibility", list(TraceVisibility))
def test_trace_visibility_accepts_every_governed_member_and_its_string(visibility):
    assert _draft(trace_visibility=visibility).trace_visibility is visibility
    assert _draft(trace_visibility=visibility.value).trace_visibility is visibility


@pytest.mark.parametrize("value", ["hidden", "Included", "", 3])
def test_trace_visibility_rejects_any_ungoverned_value(value):
    with pytest.raises(ConversationValidationError):
        _draft(trace_visibility=value)


def test_governed_vocabulary_values_match_the_approved_specification():
    assert {member.value for member in MessageRole} == {
        "user",
        "assistant",
        "tool",
        "system_event",
    }
    assert {member.value for member in MessageSource} == {
        "ui",
        "tool",
        "model",
        "system",
        "import",
    }
    assert {member.value for member in TraceVisibility} == {"excluded", "included"}


# 9. Only `user` and `system_event` are publicly writable.


def test_public_writable_roles_contains_exactly_user_and_system_event():
    assert {role.value for role in PUBLIC_WRITABLE_ROLES} == {"user", "system_event"}
    assert MessageRole.ASSISTANT not in PUBLIC_WRITABLE_ROLES
    assert MessageRole.TOOL not in PUBLIC_WRITABLE_ROLES


# 10 and 11. Defaults and the retention vocabulary.


def test_defaults_resolve_to_ui_excluded_and_active():
    draft = _draft()
    assert draft.source is MessageSource.UI
    assert draft.trace_visibility is TraceVisibility.EXCLUDED
    assert _message().source is MessageSource.UI
    assert _message().trace_visibility is TraceVisibility.EXCLUDED
    assert _conversation().retention_state is ConversationRetentionState.ACTIVE

    assert DEFAULT_MESSAGE_SOURCE is MessageSource.UI
    assert DEFAULT_TRACE_VISIBILITY is TraceVisibility.EXCLUDED
    assert DEFAULT_RETENTION_STATE is ConversationRetentionState.ACTIVE


def test_conversation_retention_state_exposes_all_five_governed_states():
    assert {member.value for member in ConversationRetentionState} == {
        "active",
        "summarized",
        "archived",
        "deletion_requested",
        "deleted",
    }


@pytest.mark.parametrize("state", list(ConversationRetentionState))
def test_retention_state_accepts_every_governed_member_and_its_string(state):
    assert _conversation(retention_state=state).retention_state is state
    assert _conversation(retention_state=state.value).retention_state is state


@pytest.mark.parametrize("value", ["purged", "Active", "", 3])
def test_retention_state_rejects_any_ungoverned_value(value):
    with pytest.raises(ConversationValidationError):
        _conversation(retention_state=value)


def test_messages_carry_no_independent_retention_state():
    """A message follows its parent conversation's lifecycle, per the spec."""
    assert "retention_state" not in _field_names(Message)
    assert "retention_state" not in _field_names(MessageDraft)


# 12. Timestamps must be timezone-aware and are normalized to UTC.


def test_timestamps_are_normalized_to_utc():
    offset = timezone(timedelta(hours=7))
    local = datetime(2026, 9, 4, 19, 0, 0, tzinfo=offset)

    conversation = _conversation(created_at=local, updated_at=local)
    assert conversation.created_at.utcoffset() == timedelta(0)
    assert conversation.created_at == local
    assert _message(created_at=local).created_at.utcoffset() == timedelta(0)
    assert _draft(created_at=local).created_at.utcoffset() == timedelta(0)


@pytest.mark.parametrize("value", [datetime(2026, 9, 4, 12, 0, 0), "2026-09-04", None])
def test_naive_or_non_datetime_timestamps_raise(value):
    with pytest.raises(ConversationValidationError):
        _conversation(created_at=value)

    with pytest.raises(ConversationValidationError):
        _conversation(updated_at=value)

    with pytest.raises(ConversationValidationError):
        _message(created_at=value)

    with pytest.raises(ConversationValidationError):
        _draft(created_at=value)


def test_utc_now_returns_timezone_aware_utc():
    moment = utc_now()
    assert moment.tzinfo is not None
    assert moment.utcoffset() == timedelta(0)


# 13. `sequence` is a positive integer assigned by storage.


@pytest.mark.parametrize("value", [1, 2, 9999])
def test_sequence_accepts_positive_integers(value):
    assert _message(sequence=value).sequence == value


@pytest.mark.parametrize("value", [0, -1, 1.5, "1", None, True])
def test_sequence_rejects_anything_but_a_positive_integer(value):
    with pytest.raises(ConversationValidationError):
        _message(sequence=value)


# 14. History query bounds.


def test_history_query_defaults_the_limit():
    query = MessageHistoryQuery(conversation_id="cv_example")
    assert query.limit == DEFAULT_HISTORY_LIMIT
    assert DEFAULT_HISTORY_LIMIT == 50
    assert query.after_message_id is None


@pytest.mark.parametrize("value", [1, 50, MAX_HISTORY_LIMIT])
def test_history_query_accepts_limits_inside_the_governed_range(value):
    assert MessageHistoryQuery(conversation_id="cv_example", limit=value).limit == value
    assert MAX_HISTORY_LIMIT == 200


@pytest.mark.parametrize("value", [0, -1, MAX_HISTORY_LIMIT + 1, 1.5, "50"])
def test_history_query_rejects_limits_outside_the_governed_range(value):
    with pytest.raises(ConversationValidationError):
        MessageHistoryQuery(conversation_id="cv_example", limit=value)


def test_history_query_strips_the_cursor_and_requires_a_conversation():
    query = MessageHistoryQuery(
        conversation_id="  cv_example  ", after_message_id="  ms_example  "
    )
    assert query.conversation_id == "cv_example"
    assert query.after_message_id == "ms_example"

    with pytest.raises(ConversationValidationError):
        MessageHistoryQuery(conversation_id="   ")


def test_history_query_treats_a_blank_cursor_as_absent():
    assert (
        MessageHistoryQuery(
            conversation_id="cv_example", after_message_id="  "
        ).after_message_id
        is None
    )


# 15. Every public name is reachable from the package root.


def test_public_contract_names_are_importable_from_the_package():
    expected = {
        "CONVERSATION_ID_PREFIX",
        "MESSAGE_ID_PREFIX",
        "TITLE_MAX_LENGTH",
        "DEFAULT_HISTORY_LIMIT",
        "MAX_HISTORY_LIMIT",
        "PUBLIC_WRITABLE_ROLES",
        "DEFAULT_MESSAGE_SOURCE",
        "DEFAULT_TRACE_VISIBILITY",
        "DEFAULT_RETENTION_STATE",
        "Conversation",
        "ConversationCreate",
        "ConversationRetentionState",
        "ConversationValidationError",
        "Message",
        "MessageDraft",
        "MessageHistoryQuery",
        "MessageRole",
        "MessageSource",
        "TraceVisibility",
        "generate_conversation_id",
        "generate_message_id",
        "require_text",
        "utc_now",
        "ConversationRepository",
        "ConversationRepositoryError",
        "ConversationAlreadyExistsError",
        "MessageSequenceConflictError",
        "ConversationStorageError",
    }
    missing = {name for name in expected if not hasattr(conversations_package, name)}
    assert missing == set()


def test_repository_error_types_form_one_hierarchy():
    from backend.conversations.repository import (
        ConversationAlreadyExistsError,
        ConversationRepositoryError,
        ConversationStorageError,
        MessageSequenceConflictError,
    )

    assert issubclass(ConversationAlreadyExistsError, ConversationRepositoryError)
    assert issubclass(MessageSequenceConflictError, ConversationRepositoryError)
    assert issubclass(ConversationStorageError, ConversationRepositoryError)
    assert issubclass(ConversationValidationError, ValueError)


def test_repository_protocol_declares_the_governed_operations():
    from backend.conversations.repository import ConversationRepository

    for operation in (
        "create",
        "get",
        "list_by_workspace",
        "append_message",
        "list_messages",
    ):
        assert hasattr(ConversationRepository, operation)


def test_require_text_is_shared_by_both_value_objects():
    assert require_text("  cv_example  ", "conversation_id") == "cv_example"

    with pytest.raises(ConversationValidationError):
        require_text("   ", "conversation_id")


def test_contracts_are_frozen_so_records_cannot_drift_after_validation():
    conversation = _conversation()
    message = _message()

    with pytest.raises(dataclasses.FrozenInstanceError):
        conversation.title = "changed"

    with pytest.raises(dataclasses.FrozenInstanceError):
        message.sequence = 99


def test_contract_module_imports_only_the_standard_library():
    """The contract layer must stay storage-agnostic and route-agnostic."""
    import sys

    import backend.conversations.models as models_module

    forbidden = ("fastapi", "pydantic", "sqlite3", "chromadb", "backend.rag")
    source_globals = vars(models_module)
    imported = {
        value.__name__
        for value in source_globals.values()
        if isinstance(value, type(sys))
    }
    assert not any(
        name.startswith(prefix) for name in imported for prefix in forbidden
    ), f"contract module imported a forbidden dependency: {imported}"
