"""Unit tests for R3 trip workspace value contracts.

These tests pin the workspace contract vocabulary defined by the approved R3
specification and ADR 0002. The contract layer must stay storage-agnostic and
route-agnostic: no FastAPI, SQLite, RAG, Chroma, model-provider, or evaluation
import may appear in it.
"""

from dataclasses import FrozenInstanceError, fields
from datetime import date, datetime, timedelta, timezone

import pytest

from backend.workspaces.models import (
    DESTINATION_SCOPE_MAX_LENGTH,
    TITLE_MAX_LENGTH,
    WORKSPACE_ID_PREFIX,
    DateWindow,
    PlanningStatus,
    RetentionState,
    TripWorkspace,
    WorkspaceCreate,
    WorkspaceListFilter,
    WorkspaceValidationError,
    generate_workspace_id,
    utc_now,
)


def _aware_now() -> datetime:
    return datetime(2026, 9, 3, 12, 0, 0, tzinfo=timezone.utc)


def _workspace(**overrides) -> TripWorkspace:
    """Build a valid TripWorkspace, overriding single fields per test."""
    payload = {
        "workspace_id": "tw_0123456789abcdef",
        "owner_user_id": "local-user",
        "title": "Da Nang family trip",
        "destination_scope": "Da Nang and Hoi An",
        "date_window": DateWindow(date(2026, 12, 20), date(2026, 12, 25)),
        "planning_status": PlanningStatus.IDEA,
        "retention_state": RetentionState.ACTIVE,
        "created_at": _aware_now(),
        "updated_at": _aware_now(),
    }
    payload.update(overrides)
    return TripWorkspace(**payload)


# 1. workspace_id is generated by storage/service, never accepted from input.


def test_workspace_create_has_no_workspace_id_field():
    field_names = {f.name for f in fields(WorkspaceCreate)}
    assert "workspace_id" not in field_names


def test_workspace_create_rejects_caller_supplied_workspace_id():
    with pytest.raises(TypeError):
        WorkspaceCreate(
            owner_user_id="local-user",
            title="Da Nang family trip",
            workspace_id="tw_caller_supplied",
        )


# 2. Generated IDs are strings prefixed with `tw_`.


def test_generate_workspace_id_uses_governed_prefix():
    workspace_id = generate_workspace_id()
    assert isinstance(workspace_id, str)
    assert workspace_id.startswith(WORKSPACE_ID_PREFIX)
    assert WORKSPACE_ID_PREFIX == "tw_"
    assert len(workspace_id) > len(WORKSPACE_ID_PREFIX)


def test_generate_workspace_id_is_unique_per_call():
    generated = {generate_workspace_id() for _ in range(50)}
    assert len(generated) == 50


# 3. owner_user_id and title are stripped and non-empty; title <= 120 chars.


def test_create_strips_owner_and_title():
    created = WorkspaceCreate(
        owner_user_id="  local-user  ",
        title="  Da Nang family trip  ",
    )
    assert created.owner_user_id == "local-user"
    assert created.title == "Da Nang family trip"


@pytest.mark.parametrize("blank", ["", "   ", "\t", "\n"])
def test_create_rejects_blank_owner(blank):
    with pytest.raises(WorkspaceValidationError):
        WorkspaceCreate(owner_user_id=blank, title="Da Nang family trip")


@pytest.mark.parametrize("blank", ["", "   ", "\t", "\n"])
def test_create_rejects_blank_title(blank):
    with pytest.raises(WorkspaceValidationError):
        WorkspaceCreate(owner_user_id="local-user", title=blank)


def test_title_accepts_maximum_length():
    created = WorkspaceCreate(
        owner_user_id="local-user",
        title="t" * TITLE_MAX_LENGTH,
    )
    assert len(created.title) == TITLE_MAX_LENGTH
    assert TITLE_MAX_LENGTH == 120


def test_title_rejects_over_maximum_length():
    with pytest.raises(WorkspaceValidationError):
        WorkspaceCreate(
            owner_user_id="local-user",
            title="t" * (TITLE_MAX_LENGTH + 1),
        )


def test_title_length_is_measured_after_stripping():
    padded = "  " + ("t" * TITLE_MAX_LENGTH) + "  "
    created = WorkspaceCreate(owner_user_id="local-user", title=padded)
    assert len(created.title) == TITLE_MAX_LENGTH


# 4. destination_scope is optional, stripped when present, <= 160 chars.


def test_destination_scope_defaults_to_none():
    created = WorkspaceCreate(owner_user_id="local-user", title="Trip")
    assert created.destination_scope is None


def test_destination_scope_is_stripped_when_present():
    created = WorkspaceCreate(
        owner_user_id="local-user",
        title="Trip",
        destination_scope="  Da Nang and Hoi An  ",
    )
    assert created.destination_scope == "Da Nang and Hoi An"


def test_blank_destination_scope_normalizes_to_none():
    created = WorkspaceCreate(
        owner_user_id="local-user",
        title="Trip",
        destination_scope="   ",
    )
    assert created.destination_scope is None


def test_destination_scope_accepts_maximum_length():
    created = WorkspaceCreate(
        owner_user_id="local-user",
        title="Trip",
        destination_scope="d" * DESTINATION_SCOPE_MAX_LENGTH,
    )
    assert len(created.destination_scope) == DESTINATION_SCOPE_MAX_LENGTH
    assert DESTINATION_SCOPE_MAX_LENGTH == 160


def test_destination_scope_rejects_over_maximum_length():
    with pytest.raises(WorkspaceValidationError):
        WorkspaceCreate(
            owner_user_id="local-user",
            title="Trip",
            destination_scope="d" * (DESTINATION_SCOPE_MAX_LENGTH + 1),
        )


# 5. Date window permits missing start/end but rejects end_date < start_date.


def test_date_window_allows_both_absent():
    window = DateWindow()
    assert window.start_date is None
    assert window.end_date is None


def test_date_window_allows_only_start():
    window = DateWindow(start_date=date(2026, 12, 20))
    assert window.start_date == date(2026, 12, 20)
    assert window.end_date is None


def test_date_window_allows_only_end():
    window = DateWindow(end_date=date(2026, 12, 25))
    assert window.start_date is None
    assert window.end_date == date(2026, 12, 25)


def test_date_window_allows_equal_start_and_end():
    same_day = date(2026, 12, 20)
    window = DateWindow(start_date=same_day, end_date=same_day)
    assert window.start_date == window.end_date


def test_date_window_rejects_end_before_start():
    with pytest.raises(WorkspaceValidationError):
        DateWindow(start_date=date(2026, 12, 25), end_date=date(2026, 12, 20))


def test_create_rejects_inverted_date_window():
    with pytest.raises(WorkspaceValidationError):
        WorkspaceCreate(
            owner_user_id="local-user",
            title="Trip",
            date_window=DateWindow(
                start_date=date(2026, 12, 25),
                end_date=date(2026, 12, 20),
            ),
        )


# 6. Default planning_status is `idea`.


def test_planning_status_defaults_to_idea():
    created = WorkspaceCreate(owner_user_id="local-user", title="Trip")
    assert created.planning_status is PlanningStatus.IDEA
    assert PlanningStatus.IDEA.value == "idea"


def test_explicit_planning_status_is_preserved():
    created = WorkspaceCreate(
        owner_user_id="local-user",
        title="Trip",
        planning_status=PlanningStatus.BOOKED,
    )
    assert created.planning_status is PlanningStatus.BOOKED


def test_planning_status_accepts_governed_string_value():
    created = WorkspaceCreate(
        owner_user_id="local-user",
        title="Trip",
        planning_status="planning",
    )
    assert created.planning_status is PlanningStatus.PLANNING


# 7. Default retention_state is `active`.


def test_retention_state_defaults_to_active():
    workspace = _workspace()
    assert workspace.retention_state is RetentionState.ACTIVE
    assert RetentionState.ACTIVE.value == "active"


def test_trip_workspace_retention_state_default_is_active_without_argument():
    workspace = TripWorkspace(
        workspace_id="tw_0123456789abcdef",
        owner_user_id="local-user",
        title="Trip",
        destination_scope=None,
        date_window=None,
        planning_status=PlanningStatus.IDEA,
        created_at=_aware_now(),
        updated_at=_aware_now(),
    )
    assert workspace.retention_state is RetentionState.ACTIVE


# 8. Unknown planning_status values are rejected.


@pytest.mark.parametrize("bad", ["draft", "retained", "unknown", "IDEA", ""])
def test_create_rejects_unknown_planning_status(bad):
    with pytest.raises(WorkspaceValidationError):
        WorkspaceCreate(
            owner_user_id="local-user",
            title="Trip",
            planning_status=bad,
        )


def test_planning_status_vocabulary_matches_approved_specification():
    assert [status.value for status in PlanningStatus] == [
        "idea",
        "planning",
        "booked",
        "active",
        "completed",
        "cancelled",
        "archived",
    ]


def test_retention_state_vocabulary_matches_approved_specification():
    assert [state.value for state in RetentionState] == [
        "active",
        "archived",
        "deletion_requested",
        "deleted",
    ]


# 9. Timestamps are timezone-aware UTC datetimes.


def test_utc_now_returns_timezone_aware_utc():
    now = utc_now()
    assert now.tzinfo is not None
    assert now.utcoffset() == timedelta(0)


def test_trip_workspace_rejects_naive_created_at():
    with pytest.raises(WorkspaceValidationError):
        _workspace(created_at=datetime(2026, 9, 3, 12, 0, 0))


def test_trip_workspace_rejects_naive_updated_at():
    with pytest.raises(WorkspaceValidationError):
        _workspace(updated_at=datetime(2026, 9, 3, 12, 0, 0))


def test_trip_workspace_normalizes_non_utc_offset_to_utc():
    plus_seven = timezone(timedelta(hours=7))
    workspace = _workspace(created_at=datetime(2026, 9, 3, 19, 0, 0, tzinfo=plus_seven))
    assert workspace.created_at.utcoffset() == timedelta(0)
    assert workspace.created_at == datetime(2026, 9, 3, 12, 0, 0, tzinfo=timezone.utc)


# TripWorkspace identity and immutability.


def test_trip_workspace_rejects_blank_workspace_id():
    with pytest.raises(WorkspaceValidationError):
        _workspace(workspace_id="   ")


def test_trip_workspace_rejects_workspace_id_without_governed_prefix():
    with pytest.raises(WorkspaceValidationError):
        _workspace(workspace_id="ws_0123456789abcdef")


def test_trip_workspace_is_immutable():
    workspace = _workspace()
    with pytest.raises(FrozenInstanceError):
        workspace.title = "changed"


def test_workspace_list_filter_requires_non_empty_owner():
    with pytest.raises(WorkspaceValidationError):
        WorkspaceListFilter(owner_user_id="   ")


def test_workspace_list_filter_strips_owner():
    filter_ = WorkspaceListFilter(owner_user_id="  local-user  ")
    assert filter_.owner_user_id == "local-user"


# 10. Public exports are importable from `backend.workspaces`.


def test_package_exports_the_workspace_stack():
    """The package re-exports what an outside caller needs to build the stack."""
    import backend.workspaces as package

    for name in (
        "DateWindow",
        "PlanningStatus",
        "RetentionState",
        "SQLiteWorkspaceRepository",
        "TripWorkspace",
        "WorkspaceCreate",
        "WorkspaceRepository",
        "WorkspaceRepositoryError",
        "WorkspaceService",
        "WorkspaceValidationError",
    ):
        assert hasattr(package, name), f"backend.workspaces must export {name}"


def test_contract_module_imports_no_infrastructure():
    """The contract layer must not couple to storage, web, or RAG concerns.

    This asserts the real import graph rather than searching the source text, so
    a mention inside a docstring cannot pass or fail the check by accident.
    """
    import ast
    from pathlib import Path

    import backend.workspaces.models as models_module

    module_file = models_module.__file__
    assert module_file is not None
    tree = ast.parse(Path(module_file).read_text(encoding="utf-8"))

    imported: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            imported.update(alias.name for alias in node.names)
        elif isinstance(node, ast.ImportFrom) and node.module:
            imported.add(node.module)

    for forbidden in (
        "fastapi",
        "pydantic",
        "sqlite3",
        "chromadb",
        "openai",
        "sentence_transformers",
        "backend.rag",
        "backend.app",
        "backend.workspaces.repository",
        "backend.workspaces.sqlite_repository",
    ):
        offenders = [name for name in imported if name.startswith(forbidden)]
        assert not offenders, f"models.py must not import {forbidden}: {offenders}"
