"""Unit tests for the R6 memory record value contracts.

These contracts are storage-agnostic and route-agnostic: the module under test
depends on the Python standard library only. Identifiers, timestamps, scope
labels, and lifecycle states are server-owned.

R5 candidate contracts are untouched by this file; Task 2 only adds the
answer-eligible record, promotion, retrieval, and trace contracts.

No test here touches a database, a model provider, Chroma, or the network.
"""

from datetime import datetime, timedelta, timezone

import pytest

import backend.memory as memory_package
from backend.memory.models import (
    MEMORY_RECORD_ID_PREFIX,
    MEMORY_PROMOTION_RUN_ID_PREFIX,
    MEMORY_RETRIEVAL_TRACE_ID_PREFIX,
    MemoryPromotionResult,
    MemoryPromotionRun,
    MemoryRecord,
    MemoryRecordScope,
    MemoryRecordStatus,
    MemoryRecordType,
    MemorySelection,
    MemorySelectionReason,
    MemorySelectionStatus,
    MemorySelectionTrace,
    MemoryValidationError,
    PromotionSkipCount,
    PromotionSkipReason,
    SensitivityLabel,
    generate_memory_promotion_run_id,
    generate_memory_record_id,
    generate_memory_retrieval_trace_id,
    utc_now,
)

MOMENT = datetime(2026, 9, 5, 12, 0, 0, tzinfo=timezone.utc)


def _record(**overrides) -> MemoryRecord:
    payload = {
        "memory_id": generate_memory_record_id(),
        "source_candidate_id": "mc_example",
        "workspace_id": "tw_example",
        "conversation_id": "cv_example",
        "source_message_id": "ms_example",
        "source_sequence": 1,
        "owner_user_id": "local-user",
        "scope": MemoryRecordScope.USER,
        "scope_id": "local-user",
        "memory_type": MemoryRecordType.PREFERENCE,
        "status": MemoryRecordStatus.ACTIVE,
        "text": "Người dùng ăn chay trường.",
        "confidence": 0.8,
        "sensitivity_label": SensitivityLabel.NONE,
        "supersedes_memory_id": None,
        "created_at": MOMENT,
        "updated_at": MOMENT,
        "expires_at": None,
    }
    payload.update(overrides)
    return MemoryRecord(**payload)


def _run(**overrides) -> MemoryPromotionRun:
    payload = {
        "promotion_run_id": generate_memory_promotion_run_id(),
        "workspace_id": "tw_example",
        "conversation_id": "cv_example",
        "source_candidate_count": 1,
        "promoted_count": 1,
        "skipped_count": 0,
        "skip_reasons": (),
        "started_at": MOMENT,
        "finished_at": MOMENT,
    }
    payload.update(overrides)
    return MemoryPromotionRun(**payload)


def _selection(**overrides) -> MemorySelection:
    payload = {
        "memory_id": generate_memory_record_id(),
        "scope": MemoryRecordScope.USER,
        "memory_type": MemoryRecordType.PREFERENCE,
        "reason": MemorySelectionReason.LEXICAL_MATCH,
        "score": 1.0,
        "text": "Người dùng ăn chay trường.",
    }
    payload.update(overrides)
    return MemorySelection(**payload)


# 1. Identity is generated by the module with governed prefixes.


def test_generated_record_identities_use_governed_prefixes():
    assert generate_memory_record_id().startswith(MEMORY_RECORD_ID_PREFIX)
    assert generate_memory_promotion_run_id().startswith(MEMORY_PROMOTION_RUN_ID_PREFIX)
    assert generate_memory_retrieval_trace_id().startswith(
        MEMORY_RETRIEVAL_TRACE_ID_PREFIX
    )
    assert MEMORY_RECORD_ID_PREFIX == "mem_"
    assert MEMORY_PROMOTION_RUN_ID_PREFIX == "mpr_"
    assert MEMORY_RETRIEVAL_TRACE_ID_PREFIX == "mtr_"


def test_record_id_rejects_wrong_prefix_and_blank():
    with pytest.raises(MemoryValidationError):
        _record(memory_id="mc_wrong")
    with pytest.raises(MemoryValidationError):
        _record(memory_id="  ")
    with pytest.raises(MemoryValidationError):
        _run(promotion_run_id="mer_wrong")


def test_blank_required_identifiers_are_rejected():
    with pytest.raises(MemoryValidationError):
        _record(source_candidate_id="")
    with pytest.raises(MemoryValidationError):
        _record(owner_user_id="   ")
    with pytest.raises(MemoryValidationError):
        _record(workspace_id="")


# 2. Governed vocabularies match the approved spec.


def test_governed_record_vocabularies():
    assert {item.value for item in MemoryRecordScope} == {
        "user",
        "workspace",
        "conversation",
    }
    assert {item.value for item in MemoryRecordType} == {
        "preference",
        "constraint",
        "profile_fact",
        "episode",
        "decision",
        "correction",
    }
    assert {item.value for item in MemoryRecordStatus} == {
        "active",
        "superseded",
        "expired",
        "archived",
        "deletion_requested",
        "deleted",
    }
    assert {item.value for item in MemorySelectionReason} == {
        "lexical_match",
        "active_correction",
    }
    assert {item.value for item in MemorySelectionStatus} == {
        "selected",
        "none_selected",
        "skipped",
    }
    assert {item.value for item in PromotionSkipReason} == {
        "promoted",
        "not_accepted",
        "scope_not_promotable",
        "type_not_promotable",
        "below_min_confidence",
        "sensitivity_not_promotable",
        "provenance_unresolved",
        "reason_not_promotable",
        "duplicate_active_record",
        "duplicate_superseded_record",
        "correction_supersedes_multiple",
    }


def test_unknown_record_values_are_rejected():
    with pytest.raises(MemoryValidationError):
        _record(scope="galaxy")
    with pytest.raises(MemoryValidationError):
        _record(status="pending")
    with pytest.raises(MemoryValidationError):
        _selection(reason="vibes")


# 3. Scope and scope_id are bound together.


def test_scope_id_must_match_its_scope_owner():
    assert _record(scope=MemoryRecordScope.USER, scope_id="local-user")
    assert _record(
        scope=MemoryRecordScope.WORKSPACE,
        scope_id="tw_example",
        memory_type=MemoryRecordType.CONSTRAINT,
    )
    assert _record(
        scope=MemoryRecordScope.CONVERSATION,
        scope_id="cv_example",
        memory_type=MemoryRecordType.EPISODE,
    )
    with pytest.raises(MemoryValidationError):
        _record(scope=MemoryRecordScope.USER, scope_id="tw_example")
    with pytest.raises(MemoryValidationError):
        _record(scope=MemoryRecordScope.WORKSPACE, scope_id="cv_example")
    with pytest.raises(MemoryValidationError):
        _record(scope=MemoryRecordScope.CONVERSATION, scope_id="tw_example")


# 4. Text, confidence, sensitivity, and lifecycle rules.


def test_record_text_is_required_and_bounded():
    with pytest.raises(MemoryValidationError):
        _record(text="   ")
    with pytest.raises(MemoryValidationError):
        _record(text="x" * 501)
    _record(text="x" * 500)


def test_record_confidence_is_a_closed_unit_interval():
    assert _record(confidence=0.0).confidence == 0.0
    assert _record(confidence=1.0).confidence == 1.0
    with pytest.raises(MemoryValidationError):
        _record(confidence=1.1)


def test_record_accepts_every_sensitivity_label_at_contract_level():
    for label in SensitivityLabel:
        assert _record(sensitivity_label=label).sensitivity_label is label


def test_record_supersession_link_is_optional_but_governed():
    assert _record().supersedes_memory_id is None
    assert _record(supersedes_memory_id="mem_older").supersedes_memory_id == "mem_older"
    with pytest.raises(MemoryValidationError):
        _record(supersedes_memory_id="mc_not_a_record")


def test_record_expiration_is_optional_but_must_be_utc():
    assert _record().expires_at is None
    later = MOMENT + timedelta(days=30)
    assert _record(expires_at=later).expires_at == later
    with pytest.raises(MemoryValidationError):
        _record(expires_at=datetime(2026, 10, 5))


def test_record_timestamps_must_be_utc():
    naive = datetime(2026, 9, 5, 12, 0, 0)
    with pytest.raises(MemoryValidationError):
        _record(created_at=naive)
    with pytest.raises(MemoryValidationError):
        _record(updated_at=naive)


# 5. Promotion run, result, selection, and trace contracts.


def test_promotion_counts_must_add_up():
    run = _run(
        source_candidate_count=3,
        promoted_count=1,
        skipped_count=2,
        skip_reasons=(PromotionSkipCount(PromotionSkipReason.NOT_ACCEPTED, 2),),
    )
    assert run.promoted_count + run.skipped_count == run.source_candidate_count
    with pytest.raises(MemoryValidationError):
        _run(source_candidate_count=1, promoted_count=1, skipped_count=1)


def test_promotion_result_carries_promoted_ids():
    result = MemoryPromotionResult(
        promotion_run_id=generate_memory_promotion_run_id(),
        workspace_id="tw_example",
        conversation_id="cv_example",
        source_candidate_count=1,
        promoted_count=1,
        skipped_count=0,
        skip_reasons=(),
        multi_target_correction_count=0,
        promoted_memory_ids=("mem_one",),
        started_at=MOMENT,
        finished_at=MOMENT,
    )
    assert result.promoted_memory_ids == ("mem_one",)
    assert result.multi_target_correction_count == 0


def test_selection_score_must_be_finite_and_non_negative():
    assert _selection(score=0.0).score == 0.0
    with pytest.raises(MemoryValidationError):
        _selection(score=-0.1)
    with pytest.raises(MemoryValidationError):
        _selection(score=float("inf"))


def test_selection_trace_binds_ids_to_reasons():
    trace = MemorySelectionTrace(
        trace_id=generate_memory_retrieval_trace_id(),
        workspace_id="tw_example",
        conversation_id="cv_example",
        gate_enabled=True,
        status=MemorySelectionStatus.SELECTED,
        selected_ids=("mem_one", "mem_two"),
        reasons=(
            MemorySelectionReason.LEXICAL_MATCH,
            MemorySelectionReason.ACTIVE_CORRECTION,
        ),
        eligible_count=2,
        created_at=MOMENT,
    )
    assert trace.selected_ids == ("mem_one", "mem_two")
    with pytest.raises(MemoryValidationError):
        MemorySelectionTrace(
            trace_id=generate_memory_retrieval_trace_id(),
            workspace_id="tw_example",
            conversation_id=None,
            gate_enabled=False,
            status=MemorySelectionStatus.SKIPPED,
            selected_ids=("mem_one",),
            reasons=(),
            eligible_count=0,
            created_at=MOMENT,
        )


def test_package_exports_stable_r6_contracts():
    for name in (
        "MemoryRecord",
        "MemoryRecordStatus",
        "MemoryPromotionRun",
        "MemoryPromotionResult",
        "MemorySelection",
        "MemorySelectionTrace",
        "generate_memory_record_id",
        "generate_memory_promotion_run_id",
    ):
        assert hasattr(memory_package, name), f"missing export: {name}"


def test_utc_now_still_returns_timezone_aware_utc():
    assert utc_now().utcoffset() == timedelta(0)
