"""Unit tests for the R5 memory candidate value contracts.

These contracts are storage-agnostic and route-agnostic: the module under test
depends on the Python standard library only. Identifiers, timestamps, and
policy vocabulary are server-owned, so no caller-supplied value can set them.

No test here touches a database, a model provider, Chroma, or the network.
"""

import dataclasses
from datetime import datetime, timedelta, timezone
from pathlib import Path

import pytest

import backend.memory as memory_package
from backend.memory.models import (
    CANDIDATE_TEXT_MAX_LENGTH,
    EVIDENCE_SUMMARY_MAX_LENGTH,
    MEMORY_CANDIDATE_ID_PREFIX,
    MEMORY_RUN_ID_PREFIX,
    MemoryCandidate,
    MemoryCandidateDraft,
    MemoryCandidateStatus,
    MemoryExtractionRun,
    MemoryExtractionTrigger,
    MemoryRunStatus,
    MemoryScope,
    MemorySourceMessage,
    MemoryType,
    MemoryValidationError,
    PolicyReason,
    SensitivityLabel,
    generate_memory_candidate_id,
    generate_memory_run_id,
    utc_now,
)

MOMENT = datetime(2026, 9, 4, 12, 0, 0, tzinfo=timezone.utc)


def _source_message(**overrides) -> MemorySourceMessage:
    payload = {
        "message_id": "ms_example",
        "conversation_id": "cv_example",
        "workspace_id": "tw_example",
        "sequence": 1,
        "role": "user",
        "source": "ui",
        "trace_visibility": "included",
        "content": "Tôi ăn chay trường.",
        "created_at": MOMENT,
    }
    payload.update(overrides)
    return MemorySourceMessage(**payload)


def _draft(**overrides) -> MemoryCandidateDraft:
    payload = {
        "source_message_id": "ms_example",
        "conversation_id": "cv_example",
        "workspace_id": "tw_example",
        "source_sequence": 1,
        "role": "user",
        "source": "ui",
        "trace_visibility": "included",
        "proposed_scope": MemoryScope.USER,
        "proposed_type": MemoryType.PREFERENCE,
        "confidence": 0.8,
        "sensitivity_label": SensitivityLabel.NONE,
        "text": "Người dùng ăn chay trường.",
        "evidence_summary": "ăn chay trường",
    }
    payload.update(overrides)
    return MemoryCandidateDraft(**payload)


def _candidate(**overrides) -> MemoryCandidate:
    payload = {
        "candidate_id": generate_memory_candidate_id(),
        "run_id": generate_memory_run_id(),
        "workspace_id": "tw_example",
        "conversation_id": "cv_example",
        "source_message_id": "ms_example",
        "source_sequence": 1,
        "proposed_scope": MemoryScope.USER,
        "proposed_type": MemoryType.PREFERENCE,
        "status": MemoryCandidateStatus.ACCEPTED,
        "confidence": 0.8,
        "sensitivity_label": SensitivityLabel.NONE,
        "text": "Người dùng ăn chay trường.",
        "evidence_summary": "ăn chay trường",
        "reason": PolicyReason.SUPPORTED_PREFERENCE,
        "created_at": MOMENT,
    }
    payload.update(overrides)
    return MemoryCandidate(**payload)


def _run(**overrides) -> MemoryExtractionRun:
    payload = {
        "run_id": generate_memory_run_id(),
        "workspace_id": "tw_example",
        "conversation_id": "cv_example",
        "trigger": MemoryExtractionTrigger.MANUAL,
        "extractor_id": "rule-based-v1",
        "policy_id": "policy-v1",
        "status": MemoryRunStatus.COMPLETED,
        "started_at": MOMENT,
        "finished_at": MOMENT,
        "candidate_count": 1,
        "accepted_count": 1,
        "rejected_count": 0,
        "needs_user_action_count": 0,
        "invalid_count": 0,
        "failure_reason": None,
    }
    payload.update(overrides)
    return MemoryExtractionRun(**payload)


# 1. Identity is generated by the module with governed prefixes.


def test_generated_identities_use_governed_prefixes():
    run_id = generate_memory_run_id()
    candidate_id = generate_memory_candidate_id()
    assert run_id.startswith(MEMORY_RUN_ID_PREFIX)
    assert candidate_id.startswith(MEMORY_CANDIDATE_ID_PREFIX)
    assert run_id != generate_memory_run_id()
    assert candidate_id != generate_memory_candidate_id()


def test_run_id_rejects_wrong_prefix_and_blank():
    with pytest.raises(MemoryValidationError):
        _run(run_id="mc_wrongprefix")
    with pytest.raises(MemoryValidationError):
        _run(run_id="   ")


def test_candidate_id_rejects_wrong_prefix_and_blank():
    with pytest.raises(MemoryValidationError):
        _candidate(candidate_id="mer_wrongprefix")
    with pytest.raises(MemoryValidationError):
        _candidate(candidate_id="")


def test_blank_required_identifiers_are_rejected():
    with pytest.raises(MemoryValidationError):
        _run(workspace_id="  ")
    with pytest.raises(MemoryValidationError):
        _candidate(source_message_id="")
    with pytest.raises(MemoryValidationError):
        _draft(conversation_id="   ")
    with pytest.raises(MemoryValidationError):
        _source_message(message_id="")


# 2. Timestamps are timezone-aware UTC.


def test_naive_datetimes_are_rejected():
    naive = datetime(2026, 9, 4, 12, 0, 0)
    with pytest.raises(MemoryValidationError):
        _source_message(created_at=naive)
    with pytest.raises(MemoryValidationError):
        _candidate(created_at=naive)
    with pytest.raises(MemoryValidationError):
        _run(started_at=naive)


def test_finished_at_is_optional_but_must_be_utc_when_present():
    run = _run(finished_at=None)
    assert run.finished_at is None
    with pytest.raises(MemoryValidationError):
        _run(finished_at=datetime(2026, 9, 4, 12, 0, 0))


def test_utc_now_returns_timezone_aware_utc():
    moment = utc_now()
    assert moment.tzinfo is not None
    assert moment.utcoffset() == timedelta(0)


# 3. Text is normalized and length-bounded.


def test_text_fields_are_stripped():
    candidate = _candidate(text="  Người dùng ăn chay.  ")
    assert candidate.text == "Người dùng ăn chay."
    message = _source_message(content="  Tôi ăn chay.  ")
    assert message.content == "Tôi ăn chay."


def test_candidate_text_limit_is_500_characters():
    assert CANDIDATE_TEXT_MAX_LENGTH == 500
    _candidate(text="x" * 500)
    with pytest.raises(MemoryValidationError):
        _candidate(text="x" * 501)


def test_evidence_summary_limit_is_240_characters():
    assert EVIDENCE_SUMMARY_MAX_LENGTH == 240
    _candidate(evidence_summary="x" * 240)
    with pytest.raises(MemoryValidationError):
        _candidate(evidence_summary="x" * 241)


# 4. Confidence is a finite float inside [0.0, 1.0].


@pytest.mark.parametrize("value", [0.0, 1.0, 0.5, 1, 0])
def test_confidence_accepts_closed_unit_interval(value):
    assert _candidate(confidence=value).confidence == float(value)


@pytest.mark.parametrize("value", [-0.1, 1.1, float("nan"), float("inf"), "high", None])
def test_confidence_rejects_outside_values(value):
    with pytest.raises(MemoryValidationError):
        _candidate(confidence=value)
    with pytest.raises(MemoryValidationError):
        _draft(confidence=value)


# 5. Governed vocabularies match the approved spec.


def test_governed_enum_values():
    assert {item.value for item in MemoryRunStatus} == {
        "completed",
        "completed_with_rejections",
        "failed",
        "invalid",
    }
    assert {item.value for item in MemoryCandidateStatus} == {
        "accepted",
        "rejected",
        "needs_user_action",
        "invalid",
    }
    assert {item.value for item in MemoryScope} == {
        "user",
        "workspace",
        "conversation",
        "none",
    }
    assert {item.value for item in MemoryType} == {
        "preference",
        "constraint",
        "profile_fact",
        "episode",
        "decision",
        "correction",
        "safety_note",
        "none",
    }
    assert {item.value for item in SensitivityLabel} == {
        "none",
        "personal",
        "sensitive",
        "secret",
        "unsafe",
    }
    assert {item.value for item in MemoryExtractionTrigger} == {
        "manual",
        "evaluation",
    }
    assert {item.value for item in PolicyReason} == {
        "supported_preference",
        "supported_constraint",
        "supported_profile_fact",
        "supported_trip_decision",
        "explicit_correction",
        "no_memory_signal",
        "ambiguous",
        "transient",
        "wrong_scope",
        "low_confidence",
        "sensitive",
        "secret_like",
        "unsupported",
        "system_generated",
        "trace_excluded",
    }


def test_unknown_enum_values_are_rejected():
    with pytest.raises(MemoryValidationError):
        _candidate(proposed_scope="galaxy")
    with pytest.raises(MemoryValidationError):
        _candidate(status="pending")
    with pytest.raises(MemoryValidationError):
        _run(trigger="automatic")


def test_raw_string_values_coerce_to_enums():
    candidate = _candidate(proposed_scope="user", status="accepted")
    assert candidate.proposed_scope is MemoryScope.USER
    assert candidate.status is MemoryCandidateStatus.ACCEPTED


# 6. Run counters are consistent, including invalid_count.


def test_run_counts_must_add_up():
    run = _run(
        candidate_count=4,
        accepted_count=1,
        rejected_count=1,
        needs_user_action_count=1,
        invalid_count=1,
    )
    assert run.candidate_count == 4


def test_run_counts_reject_mismatch_and_negatives():
    with pytest.raises(MemoryValidationError):
        _run(
            candidate_count=2,
            accepted_count=1,
            rejected_count=0,
            needs_user_action_count=0,
            invalid_count=0,
        )
    with pytest.raises(MemoryValidationError):
        _run(
            candidate_count=0,
            accepted_count=0,
            rejected_count=0,
            needs_user_action_count=0,
            invalid_count=-1,
        )


# 7. Ordering facts needed by later milestones.


def test_sequence_starts_at_one_and_rejects_zero():
    assert _source_message(sequence=1).sequence == 1
    with pytest.raises(MemoryValidationError):
        _source_message(sequence=0)
    with pytest.raises(MemoryValidationError):
        _candidate(source_sequence=0)


def test_draft_starts_unevaluated():
    draft = _draft()
    assert draft.status is None
    assert draft.reason is None


def test_package_exports_stable_contracts():
    for name in (
        "MemoryExtractionRun",
        "MemorySourceMessage",
        "MemoryCandidate",
        "MemoryCandidateDraft",
        "MemoryRunStatus",
        "MemoryCandidateStatus",
        "MemoryScope",
        "MemoryType",
        "SensitivityLabel",
        "PolicyReason",
        "MemoryExtractionTrigger",
        "generate_memory_run_id",
        "generate_memory_candidate_id",
    ):
        assert hasattr(memory_package, name), f"missing export: {name}"


def test_models_module_has_no_forbidden_dependencies():
    package_file = memory_package.__file__
    assert package_file is not None
    source = Path(package_file).parent.joinpath("models.py").read_text()
    for forbidden in (
        "backend.conversations",
        "backend.workspaces",
        "backend.rag",
        "backend.orchestration",
        "fastapi",
        "sqlite3",
    ):
        assert forbidden not in source
