"""Conversation storage interface and repository error types for milestone R4.

Per ADR 0004 product code depends on this interface rather than on SQLite
details. Route handlers, the conversation service, and the orchestrator must not
embed table DDL, SQL statements, database path creation, or connection
management.

The interface takes `after_sequence` rather than `after_message_id`, because the
service resolves a caller cursor to its stored position before delegating. The
repository therefore never has to interpret an identifier.
"""

from __future__ import annotations

from typing import Protocol

from backend.conversations.models import Conversation, Message, MessageDraft


class ConversationRepositoryError(Exception):
    """Base class for conversation storage failures."""


class ConversationAlreadyExistsError(ConversationRepositoryError):
    """A conversation with the same identity already exists in storage."""


class MessageAlreadyExistsError(ConversationRepositoryError):
    """A message with the same identity already exists in storage.

    Distinct from `MessageSequenceConflictError`: this reports a collision on the
    server-generated `message_id`, which the service retries once with a fresh
    identity, whereas a sequence conflict reports a contested turn position.
    """


class MessageSequenceConflictError(ConversationRepositoryError):
    """A message already occupies the allocated position in this conversation.

    Raised instead of overwriting or reordering a turn, because later provenance
    depends on turn order being a stored fact.
    """


class ConversationStorageError(ConversationRepositoryError):
    """Storage could not complete the requested conversation operation.

    Messages raised as this type are safe for a controlled HTTP 500 response.
    They must not carry local filesystem paths, full SQL text, credentials, or
    message content.
    """


class ConversationRepository(Protocol):
    """Persistence boundary for conversation and message records."""

    def create(self, conversation: Conversation) -> Conversation:
        """Persist a new conversation and return the stored record.

        Raises:
            ConversationAlreadyExistsError: The conversation identity is used.
            ConversationStorageError: Storage failed for another reason.
        """
        ...

    def get(self, conversation_id: str) -> Conversation | None:
        """Return the stored conversation, or None when no record exists."""
        ...

    def list_by_workspace(self, workspace_id: str) -> tuple[Conversation, ...]:
        """Return conversations for one workspace in governed order.

        Ordering is `updated_at` descending, then `created_at` descending, then
        `conversation_id` ascending. Records in `deleted` retention state are
        excluded.
        """
        ...

    def append_message(self, message: MessageDraft, message_id: str) -> Message:
        """Persist one message under a server-generated identity.

        `message_id` is generated by the service, which also owns the single
        retry on a collision, so identity generation stays in one layer for both
        conversations and messages. `MessageDraft` therefore carries neither the
        identity nor the position.

        The adapter allocates `sequence` and advances the parent conversation's
        `updated_at` inside one transaction, so a failed insert leaves neither
        the position nor the parent timestamp changed.

        Raises:
            MessageAlreadyExistsError: The message identity is already used.
            MessageSequenceConflictError: The allocated position is taken.
            ConversationStorageError: Storage failed for another reason.
        """
        ...

    def get_message(self, message_id: str) -> Message | None:
        """Return one stored message, or None when no record exists.

        The service uses this to resolve a caller's `after_message_id` cursor to
        a stored `sequence` and to reject a cursor that belongs to a different
        conversation, which is why the repository never interprets an identifier
        during a page read.
        """
        ...

    def list_messages(
        self, conversation_id: str, after_sequence: int | None, limit: int
    ) -> tuple[Message, ...]:
        """Return up to `limit` messages after `after_sequence`.

        Messages are ordered by `sequence` ascending, which is transcript
        reading order. The read is scoped to `conversation_id`, so a position
        resolved elsewhere cannot widen the result set.
        """
        ...
