"""Add memory_enabled and expires_at

Revision ID: 663badefb304
Revises: 'c11fbc6ac909'
Create Date: 2026-08-13 14:28:58.533374+00:00

"""
from typing import Sequence, Union

from alembic import op
# pyrefly: ignore [missing-import]
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '663badefb304'
down_revision: Union[str, None] = 'c11fbc6ac909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_memories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('memory_enabled', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('memory_enabled')

    with op.batch_alter_table('user_memories', schema=None) as batch_op:
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###
