"""upgrade_memory_schema_v2

Revision ID: 86a15c9c43d7
Revises: '002_add_session_title'
Create Date: 2026-08-12 06:00:58.455538+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86a15c9c43d7'
down_revision: Union[str, None] = '002_add_session_title'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_memories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('memory_id', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('memory_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('importance', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('confirmation_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('source_session_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('superseded_by', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('last_confirmed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('fact_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_user_memories_memory_id'), ['memory_id'], unique=True)
        batch_op.drop_column('fact_value')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_memories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fact_value', sa.TEXT(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_user_memories_memory_id'))
        batch_op.alter_column('fact_type',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('last_confirmed_at')
        batch_op.drop_column('last_accessed_at')
        batch_op.drop_column('superseded_by')
        batch_op.drop_column('source_session_id')
        batch_op.drop_column('confirmation_count')
        batch_op.drop_column('importance')
        batch_op.drop_column('version')
        batch_op.drop_column('status')
        batch_op.drop_column('content')
        batch_op.drop_column('memory_type')
        batch_op.drop_column('memory_id')

    # ### end Alembic commands ###
