"""Add TravelDocument model

Revision ID: c11fbc6ac909
Revises: '18119db8be21'
Create Date: 2026-08-12 14:26:41.330774+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c11fbc6ac909'
down_revision: Union[str, None] = '18119db8be21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travel_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('travel_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_travel_documents_document_id'), ['document_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travel_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_travel_documents_document_id'))

    op.drop_table('travel_documents')
    # ### end Alembic commands ###
